steps:

  # 1. Build backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/gym-management/backend:$SHORT_SHA'
      - './backend'

  # 2. Push image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/gym-management/backend:$SHORT_SHA'

  # 3. Deploy image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'gym-management-api'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/gym-management/backend:$SHORT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/gym-management/backend:$SHORT_SHA'
